services:
  postgres-finance-recette:
    image: postgres:16
    container_name: postgres-finance-recette
    environment:
      POSTGRES_DB: finance_erp_recette
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fardoujamiou
    ports:
      - "5432:5432"
    volumes:
      - postgres_finance_recette_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance_erp_recette"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finance-recette-network

  app-pfa-recette:
    image: lunebadou/app-pfa:latest
    container_name: app-pfa-recette
    depends_on:
      postgres-finance-recette:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: recette
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-finance-recette:5432/finance_erp_recette
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: fardoujamiou
      SERVER_PORT: 9898
    ports:
      - "9898:9898"
    networks:
      - finance-recette-network
    restart: unless-stopped

volumes:
  postgres_finance_recette_data:

networks:
  finance-recette-network:
    driver: bridge