spring.application.name=finance-erp

# ===============================
# CONFIGURATION DE LA BASE DE DONNEES
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_erp
spring.datasource.username=postgres
spring.datasource.password=fardoujamiou
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURATION THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# CONFIGURATION ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# ===============================
# PORT DE L'APPLICATION
# ===============================
server.port=9898
