# ===============================
# IDENTITE DE L'APPLICATION
# ===============================
spring.application.name=finance-erp

# ===============================
# CONFIGURATION DE LA BASE DE DONNEES
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_erp
spring.datasource.username=postgres
spring.datasource.password=fardoujamiou
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURATION THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# PORT DE L'APPLICATION
# ===============================
server.port=9898

# ===============================
# CONFIGURATION ACTUATOR & METRICS (PROMETHEUS)
# ===============================
# Exposition des endpoints web
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# Détails de santé (utile pour le debug)
management.endpoint.health.show-details=always

# Activation spécifique de Prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

